"""RN18 handoff-replication plan v3, phase 0 input: the EXPECTED panel of
record (metadata only). 56 paradigm-pool cells read from the panel of
record (long_harmonized_v2.parquet, ResNet18 rows) + 40 standalone-CE
cells generated by the registry rule (ce_bbresnet18, dropout 0/1,
runs 1..5 on disk = run index 0..4, rew0). model_path follows the fork's
Experiment.to_path naming. No outcome is read.

Usage (from code/): python rn18_handoff_replication/make_expected_panel.py
Output: rn18_handoff_replication/manifests/expected_panel.json
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pandas as pd

PARQUET = Path("nc_csf_predictivity/outputs/track1/dataset/"
               "long_harmonized_v2.parquet")
OUT = Path("rn18_handoff_replication/manifests/expected_panel.json")
SRC_DIR = {"cifar10": "cifar10", "cifar100": "cifar100",
           "supercifar100": "supercifar", "tinyimagenet": "tiny-imagenet-200"}
CE_SEED_BASE = 270_000


def rew_token(r: float) -> str:
    r = float(r)
    return str(int(r)) if r.is_integer() else str(r)


def main() -> None:
    df = pd.read_parquet(PARQUET)
    rn = df[df.architecture == "ResNet18"]
    cells = (rn.groupby(["paradigm", "source", "run", "reward", "dropout"])
             .size().reset_index()[["paradigm", "source", "run", "reward",
                                    "dropout"]])
    paradigm = []
    for c in cells.itertuples(index=False):
        d = int(bool(c.dropout))
        path = (f"{SRC_DIR[c.source]}_paper_sweep/{c.paradigm}_bbresnet18_"
                f"do{d}_run{int(c.run)}_rew{rew_token(c.reward)}")
        paradigm.append({"component": "paradigm_pool", "paradigm": c.paradigm,
                         "source": c.source, "run_label": int(c.run),
                         "reward": float(c.reward), "dropout": d,
                         "model_path": path, "seed_note": "single run label; "
                         "one dependence block (v3 section 3.3)"})
    ce = []
    for source, sd in SRC_DIR.items():
        for d in (0, 1):
            for run_idx in range(5):
                ce.append({"component": "standalone_ce", "paradigm": "ce",
                           "source": source, "run_label": run_idx + 1,
                           "reward": 0.0, "dropout": d,
                           "model_path": f"{sd}_paper_sweep/ce_bbresnet18_"
                                         f"do{d}_run{run_idx + 1}_rew0",
                           "seed": CE_SEED_BASE + 5 * d + run_idx})
    assert len(paradigm) == 56, len(paradigm)
    assert len(ce) == 40
    man = {"plan": "RN18 handoff-replication plan v3, section 3.3 panel of "
                   "record (expected)", "n_paradigm_pool": len(paradigm),
           "n_standalone_ce": len(ce), "cells": paradigm + ce}
    text = json.dumps(man, indent=1)
    OUT.write_text(text)
    print(f"{len(paradigm)} + {len(ce)} cells; sha256 "
          f"{hashlib.sha256(text.encode()).hexdigest()}")


if __name__ == "__main__":
    main()
